<?php
$headTitle = 'Ajax';
$this->headTitle($headTitle);

$currentLang = $this->layout()->language;
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->translate($headTitle) ?></h3>
    </div>

    <div class="col-sm-12">
        <p class="my-3">Server Time: <?= date('H:i:s') ?></p>
        <hr />
        <div id="ajax-result"></div>
        <form method="post"
              class="form-inline"
              id="user-form"
        >
            <div class="form-group">
                <label class="col-form-label">
                    <input type="text" name="firstname" class="form-control" placeholder="First Name" />
                </label>
            </div>
            <div class="form-group mx-2">
                <label class="col-form-label">
                    <input type="text" name="lastname" class="form-control" placeholder="Last Name"/>
                </label>
            </div>
            <input type="submit" name="submit" value="submit" class="btn btn-outline-secondary" />
        </form>
        <hr />
    </div>
</div>
