<?php
$headTitle = 'Sample';
$this->headTitle($headTitle);

$currentLang = $this->layout()->language;
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->translate($headTitle) ?></h3>
    </div>

    <div class="col-sm-12">
        <p class="text-danger"><?= $this->escapeHtml($this->message) ?></p>
    </div>

    <div class="col-sm-12">
        <hr />
        <a href="<?= $this->url('tutorial/sample', ['action' => 'download']) ?>" class="btn btn-info">Download</a>
        <hr />
    </div>

    <div class="col-sm-12">
        <a href="<?= $this->url('tutorial/sample', ['action' => 'page']) ?>" class="btn btn-outline-secondary">Page</a>
    </div>
</div>
