<?php

class Greeting
{
    public function sayHello($greetingWord)
    {
        return $greetingWord . ' world';
    }
}

class MyGreeting
{
    public $greeting;

    public function __construct(Greeting $greeting)
    {
        $this->greeting = $greeting;
    }
}

//$myGreeting = new MyGreeting(new Greeting);
//echo $myGreeting->greeting->sayHello('Hello');

//$di = new \Zend\Di\Di();
//$myGreeting = $di->get('MyGreeting');
//echo $myGreeting->greeting->sayHello('Hello');

?>

<?php
$headTitle = 'Tutorial';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div><?= $this->escapeHtml($this->greeting) ?></div>
        <hr />
        <div class="mb-3"><?= $this->escapeHtml($this->getTime()) ?></div>
        <div><a href="<?= $this->url('tutorial/example', ['action' => 'index']) ?>" class="btn btn-info">Example page</a></div>
        <hr />
        <!--<div><a href="<?/*= $this->url('tutorial/article', ['action' => 'index']) */?>" class="btn btn-info">Articles</a></div>-->
        <div><a href="/tutorial/article" class="btn btn-info">Articles</a></div>
        <hr />
        <!--<div><a href="/tutorial/articles" class="btn btn-info">Articles regex</a></div>-->
        <div><a href="/tutorial/shuffle" class="btn btn-info">Shuffle</a></div>
        <hr />
    </div>
</div>
