<?php
$headTitle = 'View Template Page';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
        <?php

        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s id="message-box">
             <button type="button" class="close pt-3" data-dismiss="alert" aria-hidden="true">
                 &times;
             </button>
             <ul class="list-unstyled pt-3"><li>')
             ->setMessageSeparatorString('</li><li>')
             ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger', 'fade', 'show'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info', 'fade', 'show'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning', 'fade', 'show'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success', 'fade', 'show'));

        ?>
        <hr />
        <form action="<?= $this->url('tutorial/example') ?>" method="post" class="form-inline">
            <div class="form-group">
                <label class="col-form-label">
                    <input type="text" name="title" class="form-control" />
                </label>
            </div>
            <input type="submit" name="submit" value="submit" class="btn btn-secondary" />
        </form>
        <hr />
        <p>URL: <?= $this->escapeHtml($this->url) ?></p>
        <div><a href="<?= $this->url('tutorial/example', ['action' => 'sample']) ?>">Sample</a></div>
        <hr />
        <div><?= $this->widget ?></div>
    </div>
</div>

