<?php
$headTitle = 'Category: ' . $this->escapeHtml($category->getName());
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-lg-3"><div class="fixed app-nav"><?= $this->getCategories() ?></div></div>
    <div class="col-lg-9">

        <?php if ( ! is_array($this->articles) || count($this->articles) == 0 ) : ?>
            <h5>Category is empty</h5>
        <?php else : ?>

            <?php foreach ($this->articles as $article) : ?>
                <div class="card mb-4">
                    <img src="<?= $article->getImage() ?>" class="card-img-top img-fluid" alt="image">
                    <div class="card-body">
                        <h3 class="card-title"><?= $article->getTitle() ?></h3>
                        <p class="card-text"><?= $article->getDescription() ?></p>
                        <a href="<?= $this->url('blog/b', ['action' => 'page', 'id' => $article->getId()]) ?>" class="btn btn-sm btn-outline-secondary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">Posted on <?php date( 'F d, Y' ); ?> by
                        <a href="#">Author</a>
                    </div>
                </div>
            <?php endforeach; ?>

        <?php endif; ?>
    </div>
</div>

