<?= $this->doctype() ?>

<html lang="en"> <!--  lang="en" very important (did not fork form file upload without it) -->
<head>
    <meta charset="utf-8">
    <?= $this->headTitle() ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/lux-bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.2.1.min.js'))
        ->prependFile($this->basePath('js/popper.min.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <?php
                echo $this->navigation('top_navigation')->menu()
                                                        ->setUlClass("navbar-nav mr-auto")
                                                        ->setPartial('partial/top-menu')
                                                        ->render()
            ?>
        </div>
    </div>
</nav>

<div class="container">
    <?= $this->content ?>
</div>
<footer class="footer">
    <hr>
    <div class="container">
        <div class="footer-text">&copy; 2005 - <?= date('Y') ?> by PHP-User. All rights reserved.</div>
    </div>
</footer>
<?= $this->inlineScript() ?>
</body>
</html>
