<?php
$headTitle = 'Blog';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-3">
        <h3><?= $headTitle ?></h3>
    </div>
    <div class="col-sm-9">
        <?php foreach ($this->articles as $article) : ?>

            <div class="card mb-4">
                <img src="<?= $article->getImage() ?>" class="card-img-top img-fluid" alt="image">
                <div class="card-body">
                    <h3 class="card-title"><?= $article->getTitle() ?></h3>
                    <p class="card-text"><?= $article->getDescription() ?></p>
                    <a href="#" class="btn btn-sm btn-outline-secondary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">Posted on <?php date( 'F d, Y' ); ?> by
                    <a href="#">Author</a>
                </div>
            </div>


        <?php endforeach; ?>
    </div>
</div>
