<?php
$headTitle = 'Admin';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>

        <p>You have the following capabilities:</p>
        <ul class="list-unstyled">
            <li><a href="/admin/categories">Manage Categories</a></li>
            <li><a href="/admin/articles">Manage Articles</a></li>
            <li><a href="/admin/users">Manage Users</a></li>
        </ul>
    </div>
</div>
