<?php
$headTitle = 'Home page';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $headTitle ?></h3>
        <div><?= $this->escapeHtml($this->date) ?></div>
        <div class="mt-4">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d49383.105965948766!2d-82.11989542808985!3d39.32352215369553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88487a8a2843c5d3%3A0x30b0012f06624a2b!2sAthens%2C+OH+45701!5e0!3m2!1sen!2sus!4v1520273180947" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>
